# Example: Managed PostgreSQL with a database and an application user

terraform {
  required_providers {
    cubepath = {
      source  = "cubepathinc/cubepath"
      version = "~> 0.8"
    }
  }
}

provider "cubepath" {}

variable "project_id" {
  type = number
}

# Plans are per location; sizes and prices are per node
data "cubepath_managed_database_plans" "pg" {
  engine        = "postgresql"
  location_name = "eu-bcn-1"
}

resource "cubepath_managed_database" "main" {
  project_id = var.project_id
  name       = "app-db"
  engine     = "postgresql"
  version    = "17.5.0"
  plan_uuid  = data.cubepath_managed_database_plans.pg.plans[0].uuid # cheapest
  replicas   = 2
  protected  = true # set to false before destroying it

  backup_schedule_cron  = "0 3 * * *"
  backup_retention_days = 7

  # Only the parameters the platform allows; values are strings
  config = {
    work_mem          = "8192"
    statement_timeout = "30000"
  }
}

resource "cubepath_managed_database_database" "app" {
  managed_database_id = cubepath_managed_database.main.id
  name                = "app"
}

# The password is generated by the platform and only stored in the Terraform state
resource "cubepath_managed_database_user" "app" {
  managed_database_id = cubepath_managed_database.main.id
  username            = "app"
}

output "connection" {
  value = {
    host     = cubepath_managed_database.main.endpoint_host
    port     = cubepath_managed_database.main.endpoint_port
    database = cubepath_managed_database_database.app.name
    user     = cubepath_managed_database_user.app.username
  }
}

output "app_password" {
  value     = cubepath_managed_database_user.app.password
  sensitive = true
}
